import React, { useRef, useEffect } from 'react'
import { convertLocalLinksToNewTab } from '../utils/convertLocalLinksToNewTab'
import { Markdown } from './Markdown'

export function HintContent(): JSX.Element {
  const contentRef = useRef<HTMLDivElement>(null)

  useEffect(
    () => {
      convertLocalLinksToNewTab(contentRef.current)
    },
    [contentRef]
  )

  return (
    <Markdown
      ref={contentRef}
      dangerouslySetInnerHTML={{
        __html:
          '<h3 class="code-line"  data-line-start="0"  data-line-end="1" ><a id="Obsah_Npovdy_0"></a>Obsah Nápovědy</h3>\n' +
          '<p class="has-line-data" data-line-start="2" data-line-end="19">1.0. O tezauru<br />\n' +
          '1.1. Ovládání aplikace<br />\n' +
          '1.2. Druhy hesel v tezauru<br />\n' +
          '1.3. Kontakty<br />\n' +
          '2.0. Úvod k obsahu a struktuře<br />\n' +
          '2.1. Teorie a přístupy (1)<br />\n' +
          '2.2. Terénní metody (2)<br />\n' +
          '2.3. Metody zpracování (3)<br />\n' +
          '2.4. Hraniční a příbuzné obory (4)<br />\n' +
          '2.5. Chronologie (5)<br />\n' +
          '2.6. Areály (6)<br />\n' +
          '2.7. Objekty (7)<br />\n' +
          '2.8. Předměty (8)<br />\n' +
          '2.9. Historická etnika a území, státní útvary a panovnické dynastie (9)<br />\n' +
          '2.10. Povolání a pracovní činnosti (10)<br />\n' +
          '2.11. Společnost (11)<br />\n' +
          '3.0. Bibliografický soupis literatury</p>\n' +
          '<h3 class="code-line"  data-line-start="21"  data-line-end="22" ><a id="10_O_tezauru_21"></a>1.0. O tezauru</h3>\n' +
          '<p class="has-line-data" data-line-start="22" data-line-end="27">Tezaurus archeologické terminologie (TEATER) je výstupem přidružené aktivity “Mapa předmětových hesel – referenční pomůcka pro katalogizaci odborné archeologické literatury” financované ze Strategie AV21 a zároveň vznikl v rámci projektu Archeologický informační systém České republiky (AIS CR; LM2015080). Primární důvod vzniku TEATERu byla pomoc knihovníkům odborných knihoven při katalogizaci archeologické literatury a rešeršní činnosti. Proto TEATER využívá předmětových hesel z <a href="https://aleph.nkp.cz/F/?func=file&amp;file_name=find-b&amp;local_base=aut">Databáze národních autorit NK ČR</a>. Během vzniku tezauru a vývoje databáze a vyhledávací aplikace se začaly rýsovat další možné skupiny uživatelů. Díky struktuře a doprovodným informacím mohou TEATER využívat studenti archeologických kateder a ústavů i poučení laikové se zájmem o obor. Na rozdíl od fyzických terminologických slovníků archeologie nejsou hesla v tezauru řazena abecedně, ale jsou seskupena do hierarchicky uspořádaných tematických celků. Uživatel tak nemusí procházet celý tezaurus, ale pouze dílčí část obsahu, o kterou má zájem. Snahou autorů bylo hesla doplnit co největším počtem referenčních informací z příruček a encyklopedických děl, hesla doprovázejí anglické a české ekvivalenty.<br />\n' +
          'TEATER je primárně určen knihovníkům, kteří pracují s archeologickou literaturou. Má jim sloužit jako referenční nástroj v podobě webové aplikace, která rychle dodá informace ve formě hesel nebo dalších referenčních informací při katalogizaci, rešeršní práci apod.<br />\n' +
          'Pro uživatele knihoven (ať už z řad studentů, vědců nebo veřejnosti) s archeologickým fondem je TEATER nástroj ke snadnějšímu vyhledávání archeologických publikací. Jedním z účelů hesel obsažených v tomto tezauru je jejich použití při věcném popisu publikací, hesla obsažená v tomto tezauru lze tedy použít při vyhledávání literatury za pomocí OPAC katalogu.<br />\n' +
          'TEATER dá studentům (nejen) prvních ročníků archeologie tematicky uspořádané základní terminologické penzum i s doprovodnými informacemi. Webová aplikace je v částečně responzivním režimu a lze ji použít také na mobilních zařízeních. Řazení jedenácti základních kategorií přitom respektuje deduktivní postup vědecké práce, kdy z teorie a různých archeologických přístupů (první kategorie) vznikají otázky a hypotézy, které se snaží zodpovědět terénní výzkum (druhá kategorie) a následné analýzy dat a nálezů (třetí kategorie). Čtvrtá kategorie dává tezauru interdisciplinární přesah od geologie po religionistiku. Poté jsou zařazeny další archeologické kategorie (chronologie, areály, objekty, předměty), následovány pomocně-historickými kategoriemi.<br />\n' +
          'Dalším cílem projektu je také zpřístupnit laické veřejnosti se zájmem o archeologii základní terminologické penzum i s doprovodnými informacemi.</p>\n' +
          '<h4 class="code-line"  data-line-start="28"  data-line-end="29" ><a id="11_Ovldn_aplikace_28"></a>1.1. Ovládání aplikace</h4>\n' +
          '<p class="has-line-data" data-line-start="29" data-line-end="33">TEATER je volně přístupný jednotlivcům i institucím. Pro jeho použití není třeba si zřizovat účet nebo stahovat jakoukoli aplikaci. Na úvodní stránce vyhledávací aplikace se nalézají dvě základní funkce, s jejichž pomocí je uživatel schopen najít a využít obsah tezauru. Je to možnost procházet hierarchickou strukturou hesel tím, že zvolí jednu z jedenácti základních kategorií (“browse”), nebo možnost full-textového vyhledávání hesel (“search”).<br />\n' +
          'Výběr jedné z jedenácti základních kategorií uživatele přenese do hlavní části aplikace, kde jsou ve třech sloupcích zobrazeny všechny potřebné informace. Tlačítko s logem TEATERu vrátí uživatele zpátky na úvodní stránku. V levém sloupci se nachází úroveň hierarchie vybraného (tučně zvýrazněno). Prostřední sloupec obsahuje hesla podřazená vybranému heslu. Značka “+” u hesel znamená, že daný termín obsahuje jemu hierarchicky podřazené termíny v nižších úrovních. Obsah prvního a druhého sloupce se dynamicky obměňuje v závislosti na tom, jak se uživatel zanořuje hlouběji do struktury tezauru. V prvním sloupci se vždy nacházejí termíny na stejné úrovni s vybraným, v druhém jsou pak termíny hierarchicky podřazené. Ve třetím sloupci se zobrazují referenční informace k daným heslům.<br />\n' +
          'Nad sloupci se nachází drobečková navigace, která uživateli ukazuje, kde přesně se ve struktuře tezauru nalézá, a také slouží jako možnost k přechodu na jakoukoli z vyšších úrovní kliknutím myši. Hierarchie hesel je nastavená tak, aby pomohla uživateli při rešerších nebo uživatelském vyhledávání tím, že sama nabízí možnost jak vyhledávací dotaz v OPAC katalogu zúžit (dotaz byl příliš široce zvolen a přinesl velké množství výsledků), nebo naopak rozšířit (dotaz byl příliš úzce zvolen a přinesl málo výsledků). Tlačítko “Vymazat vyhledávání” opět vrátí uživatele na úvodní stranu.<br />\n' +
          'Full-textové vyhledávání obsahuje našeptávač, který již během psaní dynamicky zobrazuje předpokládané výsledky včetně toho, zda se hledaný výraz nalézá v kategoriích jako heslo (“Kategorie”) nebo pouze v referenčních informacích (“Metadata”). Při vyhledání více výsledků je možné je zobrazit všechny najednou (stiskem klávesy enter nebo pomocí tlačítka „Hledat“) nebo pomocí kurzoru vybrat jen jeden. Výsledky jsou řazeny do dvou sloupců, v levém se nalézají výsledky z názvů hesel, v pravém výsledky z referenčních informací. V případě víceslovných výrazů hledá aplikace primárně podle prvního výrazu a zároveň má implicitně nastavený operátor “OR”. Pokud chce uživatel omezit výsledky, může zadat operátor “AND”, aby aplikace vyhledala pouze oba výskyty současně, případně operátor “NOT” k vyloučení konkrétních výsledků, které za operátor uživatel zadá.</p>\n' +
          '<h4 class="code-line"  data-line-start="34"  data-line-end="35" ><a id="12_Druhy_hesel_v_tezauru_34"></a>1.2. Druhy hesel v tezauru</h4>\n' +
          '<p class="has-line-data" data-line-start="35" data-line-end="36">V tezauru se nalézají tři druhy hesel, odlišené svým podbarvením:</p>\n' +
          '<ul>\n' +
          '<li class="has-line-data" data-line-start="36" data-line-end="37">modrá hesla pouze strukturují tezaurus, nejsou to tedy odborné termíny, nenesou žádné referenční informace a nezobrazují se ve výsledcích full-textového vyhledávání.</li>\n' +
          '<li class="has-line-data" data-line-start="37" data-line-end="38">zelená hesla pocházejí z rejstříku národních autorit a běžně se užívají v katalogizační praxi knihoven. Jsou tedy pro všechny knihovny standardizovaná.</li>\n' +
          '<li class="has-line-data" data-line-start="38" data-line-end="40">oranžová hesla jsou termíny, které se v rejstříku národních autorit nenalézají. Jejich používání v katalogizační praxi je vázáno na místní lokální rejstřík dané knihovny, a není tak zaručeno jejich univerzální užití. Toto jsou fakta důležitá pro první dvě výše zmíněné skupiny uživatelů a pro užití tezauru v knihovnické praxi. V případě užití tezauru jako elektronické příručky není původ hesel (národní autority, lokální rejstřík) pro uživatele podstatný.</li>\n' +
          '</ul>\n' +
          '<h4 class="code-line"  data-line-start="40"  data-line-end="41" ><a id="13_Kontakty_40"></a>1.3. Kontakty</h4>\n' +
          '<p class="has-line-data" data-line-start="41" data-line-end="42">V případě jakéhokoli problému, ať už s chodem aplikace nebo obsahem, pište na adresu <a href="mailto:teater@arub.cz">teater@arub.cz</a>. Autoři TEATERu stejně tak ocení jakoukoli zpětnou vazbu, zejména k chodu vyhledávací aplikace a obsahu samotného tezauru. Aktualizace obsahu jsou naplánovány v půlročních cyklech, počínaje začátkem roku 2020.</p>\n' +
          '<h3 class="code-line"  data-line-start="43"  data-line-end="44" ><a id="20_vod_k_obsahu_a_struktue_43"></a>2.0. Úvod k obsahu a struktuře</h3>\n' +
          '<p class="has-line-data" data-line-start="44" data-line-end="46">Tezaurus archeologické terminologie je co do složení hesel kompromisem mezi modulární strukturou hesláře Archeologické mapy ČR (ten je postaven na principu co nejmenších jednotek a možnosti jejich vzájemného kombinování) na jedné straně a nepružným principem národních autorit na straně druhé. Je to tedy kompromis mezi tím, jak co nejvíce využít předmětová hesla z národních autorit na jedné straně a vlastní archeologickou terminologii na straně druhé.<br />\n' +
          'Klasifikační princip uplatněný během tvorby tezauru je jednak podřízený oboru archeologie a jednak logice vědecké práce. Proto jsou třeba všechny historické písemnosti pořád klasifikovány jako „předměty“ a nacházejí se tudíž v hlavní větvi č. 8, nikoli u pomocných věd historických, historiografie nebo religionistiky. Podobně všechny přírodovědné analýzy byly vyňaty ze svých mateřských oborů (nacházejících se většinou v hlavní větvi č. 4) a sdruženy do hlavní větve č. 3 (Metody zpracování). Výjimky se nacházejí u hesel patřících do kunsthistorie a vážících se zároveň na nějaké etnikum nebo národ.</p>\n' +
          '<h4 class="code-line"  data-line-start="47"  data-line-end="48" ><a id="21_Teorie_a_pstupy_1_47"></a>2.1. Teorie a přístupy (1)</h4>\n' +
          '<p class="has-line-data" data-line-start="48" data-line-end="50">První hlavní větev v logické struktuře databáze obsahuje pojmy k obecným i oborovým (archeologických) východiskům. Respektuje tak vědecký deduktivní přístup, kdy z určitých východisek a teorie vědec vytváří otázky a hypotézy pro svůj výzkum, aby je pak v dalších krocích své práce zkoumal. Větev obsahuje dvě hlavní kategorie – jsou to hesla týkající vědy obecně a pak základní pojmy a přístupy archeologie. Do obecných hesel vědy jako takové byly zahrnuty pojmy (metody nebo přístupy), které jsou používány více vědními disciplínami. Týká se to například strukturalismu, který vznikl jako lingvistický přístup, ale následně se rozšířil do široké škály vědních oborů, nebo vědeckých metod/postupů, které využívá více vědních oborů (heuristika, analýza, atd.).<br />\n' +
          'Část věnovaná archeologii pak obsahuje základní pojmy archeologické teorie (např. druhy archeologických pramenů) a také kvůli dnes široké škále specializací archeologické subobory. Ty jsou dvojího druhu: a) chronologické, historické (slovanská archeologie, klasická archeologie, atd.); b) průřezové, tematické (environmentální archeologie, montánní archeologie, atd.).</p>\n' +
          '<h4 class="code-line"  data-line-start="51"  data-line-end="52" ><a id="22_Ternn_metody_2_51"></a>2.2. Terénní metody (2)</h4>\n' +
          '<p class="has-line-data" data-line-start="52" data-line-end="53">Druhá hlavní větev obsahuje hesla týkající se terénního získávání dat. Struktura větve odpovídá modernímu pojetí archeologického výzkumu a zahrnuje v sobě i hesla, která byla dříve řazena pod archeologickou prospekci, která byla brána jako přípravná činnosti k samotnému výzkumu. Dnešní pojetí nedestruktivních metod je takové, že mohou být kromě svého prospekčního aspektu prováděny jako výzkum sám o sobě. Větev je členěna do tří subvětví a to na základně míry zasahování do archeologické situace (nedestruktivní, málo destruktivní a destruktivní metody).</p>\n' +
          '<h4 class="code-line"  data-line-start="54"  data-line-end="55" ><a id="23_Metody_zpracovn_3_54"></a>2.3. Metody zpracování (3)</h4>\n' +
          '<p class="has-line-data" data-line-start="55" data-line-end="57">Třetí hlavní větev obsahuje pojmy, které se týkají zpracování dat a nálezů, získaných výzkumem (viz předchozí větev). Pojetí větve je celostní – jsou zde hesla jak klasických archeologických činností (dokumentace, typologie, datování) tak hesla umožněná rozvojem přírodních věd a informačních technologií ve druhé polovině 20. století. Proto se zde nalézají hesla na kvantitativní statistické zpracování dat a hesla k přírodovědným analýzám a posudkům, které často provádějí specialisté z daných disciplín. Zahrnuty jsou také hesla popisující další zpracování archeologických nálezů, tedy konzervátorsko-restaurační metody a hesla vážící se ke dvěma typům institucí, které pečují o movité památky (muzea) a nemovité památky (památková péče).<br />\n' +
          'Tento celostní přístup byl při koncipování struktury větve prioritou, proto mu byla dána přednost při zařazování jednotlivých analýz a posudků do této větvě místo k jejich mateřským oborům, jinak obsaženým v hlavní větvi č. 4.</p>\n' +
          '<h4 class="code-line"  data-line-start="58"  data-line-end="59" ><a id="24_Hranin_a_pbuzn_obory_4_58"></a>2.4. Hraniční a příbuzné obory (4)</h4>\n' +
          '<p class="has-line-data" data-line-start="59" data-line-end="62">Čtvrtá hlavní větev poskytuje tezauru základní mezioborový přesah nutný ke katalogizování archeologických publikací. Je rozdělena do dvou hlavních částí přičemž v první části jsou sdruženy hesla hraničních oborů (archeobiologie, etnoarcheologie) a ve druhé (obsáhlejší) části potom hesla k oborům příbuzným a to v rozsahu od věd o Zemi (geologie) po vědy humanitní (dějiny umění, religionistika). Pro část s hesly příbuzných oborů přitom platí:<br />\n' +
          'a) jejich výběr jde do menší hloubky než v případě hesel z archeologie<br />\n' +
          'b) byla snaha je strukturovat jednotně do stejných kategorií - (základní) subobory; předmět; metody. Výjimka z tohoto byla učiněna v případě geologie a pomocných věd historických, kde je struktura podřízena jejím (mnohým) suboborům. c) Z této větve byly vyčleněny hesla týkající se jednotlivých přírodovědných analýz a byla seskupena dohromady do části ve větvi č. 3 (Metody zpracování).</p>\n' +
          '<h4 class="code-line"  data-line-start="63"  data-line-end="64" ><a id="25_Chronologie_5_63"></a>2.5. Chronologie (5)</h4>\n' +
          '<p class="has-line-data" data-line-start="64" data-line-end="67">Pátá hlavní větev obsahuje hesla k chronologii archeologické, historické a geologické. Archeologická chronologie odpovídá středoevropskému prostoru – neplatí tedy ani pro jižní oblasti Balkánského poloostrova ani pro severní Evropu. Archeologická chronologie obsahuje i archeologické kultury. Pokud jde o geografický klíč výběru kultur – z prostoru Čech, Moravy a sousedních zemí jsem byla snaha zařadit všechny archeologické kultury, z prostoru západní Evropy jen výběrový vzorek. Nebylo možné pominout balkánský, černomořský a jihoruský prostor. Tato oblast byla pokryta podrobněji než západní Evropa. Při zpracování kulturně (horizontálně) geografické řady: „civilizace; kulturní okruh (komplex); kultura; skupina“ (řazeno od pojmu s největším rozsahem po nejmenší), se práce zastavila na úrovni „kultur“; „skupiny“ obvykle nebyly zpracovány, a pokud byly použity, tak opět jen výjimečně. Kde to bylo možné a dohledatelné, je heslům přiřazena datace a v případě kultur i geografická lokalizace. Nutno zdůraznit, že obojí má orientační charakter a má dát uživateli přibližnou představu, nikoli pevné a neměnné údaje.<br />\n' +
          'Historiografická chronologie se od archeologické liší jak svým členěním, tak geografickým záběrem. Zatímco archeologie nevyužívá písemné prameny, pro historiografii jsou hlavním (nikoli ale jediným) typem pramenů. Protože je historiograficky možné zkoumat až civilizace, které začaly používat písmo, je datování (a lokalizace) starověku svázáno se vznikem blízkovýchodních civilizací kolem počátku 4. tis. př. Kr. Obě chronologie mohou mít body, kde se mohou setkat (středověk), ale je třeba je rozlišovat.<br />\n' +
          'Jako třetí typ chronologie se v této větvi nachází také geologická chronologie pro katalogizování publikací zaměřených převážně na geologii. Chybí jí jemnější klimatologické  členění holocénu (Preboreál, Boreál, Atlantik, Subboreál, Subatlantik). Pokud bude toto členění shledáno na základě zpětné vazby potřebné, bude zapracováno do další verze.</p>\n' +
          '<h4 class="code-line"  data-line-start="68"  data-line-end="69" ><a id="26_Arely_6_68"></a>2.6. Areály (6)</h4>\n' +
          '<p class="has-line-data" data-line-start="69" data-line-end="75">Šestá hlavní větev a sedmá hlavní větev databáze jsou komplementární – v šesté větvi se nacházejí hesla týkající se areálů, v sedmé hlavní větvi jsou potom sdružena hesla s jednotlivými objekty. Struktura a do značné míry i obsah obou větví byl převzat z hesláře k AMČR. Kategorizace obou (resp. i větve č. 8 - Předměty) se zakládá na základě funkčního hlediska. Rozdělení vychází z teorie sídelních areálů Evžena Neustupného (2010, s. 150-151), který ji postavil proti starší teorii využívající bodových míst (sídliště, pohřebiště):<br />\n' +
          '    „<em>Některé areály aktivit nemusí zanechat žádné archeologicky odhalitelné stopy, nebo jsou jejich doklady obtížně identifikovatelné. Takové areály aktivit by se přesto mely brát do úvahy. Protože se lze domnívat, že pravěcí lide využívali nějakým způsobem velké části své krajiny, jednotlivé komunitní areály ji musely v mnoha případech pokrývat téměř souvisle.</em><br />\n' +
          '<em>To je nejhlubší rozdíl mezi teorii komunitních areálů a empirickým pohledem na prostorovou organizaci nálezů. Empirická teorie pracuje v terminech nalezišť a případně mimonalezištních míst (,off-site&quot;) vyznačených konkrétními archeologickými nálezy. ,Naleziště“ třídí na sídliště, pohřebiště a hradiště. Archeologickou krajinu pak representuji na archeologických mapách buď body nebo malé nesouvislé plochy.</em><br />\n' +
          '<em>Teorie komunitních areálů naopak sociální krajinu uvazuje jako souvisle zasídlené území, v němž téměř každé místo melo v minulosti specifickou roli (účel, nikoliv nezbytné praktickou funkci). V takové situaci archeologická mapa přestává popisovat krajinu v terminech jednotlivých bodu reprezentujících „naleziště“. Krajina se stává bohatě strukturovaným prostorem, jehož vetší část zaujímají sídelní areály (Kuna 1991). Mapa sídelních areálů vyjadřuje míru, v jaké si pravěcí lidé přisvojili nějaké území.</em><br />\n' +
          '<em>Tento postup sám o sobě vyvolává zájem o areály aktivit (a případně o celé komunitní areály), pro něž v současné době nemáme lokálně žádné empirické doklady, ale jejichž existenci v minulosti musíme předpokládat na teoretickém základě: pole, pastviště, zdroje palivového dříví, areály specializované výroby apod. Takový přístup se už ukázal byt produktivní.</em><br />\n' +
          '<em>Tradiční pojem naleziště a tzv. mimonalezištních nálezů (,off-site“) je více či méně kvalitativní, což typicky dokumentují mapy sestavené z bodů. V protikladu k tomu pojem sídelního areálu vede ke kvantitativním úvahám. Spočívá to nejen ve zjišťovaní velikosti celých sídelních areálů, ale rovněž velikosti jednotlivých areálů aktivit a v jejich srovnávání s demografickými parametry populací, které obývaly jednotlivé komunitní areály (srov. Neustupný 1981 b, 1982a, 1983a, b, Holodňák 1987a, Waldhauser 1981).</em>“ Obdobně také viz Neustupný (2007, s. 36-37) nebo Kuna a kol. (2007, s. 12-13)</p>\n' +
          '<h4 class="code-line"  data-line-start="76"  data-line-end="77" ><a id="27_Objekty_7_76"></a>2.7. Objekty (7)</h4>\n' +
          '<p class="has-line-data" data-line-start="77" data-line-end="78">Sedmá hlavní větev seskupuje objekty, které se vyskytují v rámci jednotlivých areálů. Základní kategorizace je opět funkční hledisko. Součástí struktury větve jsou hesla, která postihují konstrukční a materiálové hledisko objektů (podvětev „specifikace objektu“).</p>\n' +
          '<h4 class="code-line"  data-line-start="79"  data-line-end="80" ><a id="28_Pedmty_8_79"></a>2.8. Předměty (8)</h4>\n' +
          '<p class="has-line-data" data-line-start="80" data-line-end="82">Osmá hlavní větev obsahuje hesla týkající se předmětů. Ty jsou kategorizovány na základě své funkce (ekofakty, militaria, součásti oděvu, šperky) bez ohledu na materiál. Přiložen je seznam hesel týkajících se materiálů. Zde je třeba podotknout, že mezi významem některých hesel týkajících se keramických materiálů (keramika, majolika, porcelán) je mezi národními autoritami Národní knihovny ČR a klasifikace, ze které tato větev vycházela, rozdíl. Zatímco zde jsou tyto hesla použity ve smyslu materiálu, národní autority je používají pro hotové produkty. I přesto bylo rozhodnuto zařadit některá sousloví, která sice narušují tuto systematiku, ale pro katalogizaci jsou užitečná (pravěká keramika, slovanská keramika, atd.).<br />\n' +
          'Co se týče komentářů – ze slovníků Karla Sklenáře byly převzaty pouze definice, morfologická typologie nemá pro katalogizační praxi význam. Jediná typologie, která byla cca ve třech případech ocitována, se týkala funkce předmětu, nikoli jeho morfologie (kování). U každé citace je odkaz na patřičné stránky z terminologického slovníku, pokud by uživatel morfologickou typologii potřeboval.</p>\n' +
          '<h4 class="code-line"  data-line-start="83"  data-line-end="84" ><a id="29_Historick_etnika_a_zem_sttn_tvary_a_panovnick_dynastie_9_83"></a>2.9. Historická etnika a území, státní útvary a panovnické dynastie (9)</h4>\n' +
          '<p class="has-line-data" data-line-start="84" data-line-end="86">V této větvi jsou abecedně seřazena hesla týkající se historicky doložených etnik a státních útvarů. Geografický záběr větve je oblast Evropy s přilehlou částí asijského Ruska, jejíž turkické národy dění v Evropě ovlivňovaly a pokud jde o klíč výběru etnik, snažili jsme se vybrat etnika nebo kmeny, které v současné podobě už neexistují. Takže jsou zde např. jednotlivé germánské kmeny (Langobardi, Frankové, Sasové), které dnes ale netvoří žádný politický celek a které svůj primárně etnický charakter ztratily už v raném středověku. Naopak zde nejsou hesla týkající se moderních národů (francouzská/é/ý ***; německá/é/ý ***; bulharská/é/ý *** atd.) – myslíme, že tento typ předmětových hesel je snadno dohledatelný.<br />\n' +
          'V této větvi jsou také zařazena hesla se středověkými a raněnovověkými panovnickými dynastiemi z prostoru středovýchodní Evropy a základní výběr hesel z historické geografie (který bude v druhém kole heuristiky dále rozšířen).</p>\n' +
          '<h4 class="code-line"  data-line-start="87"  data-line-end="88" ><a id="210_Povoln_a_pracovn_innosti_10_87"></a>2.10. Povolání a pracovní činnosti (10)</h4>\n' +
          '<p class="has-line-data" data-line-start="88" data-line-end="89">Desátá hlavní větev obsahuje hesla týkající se povolání a pracovních činností. Ty jsou seskupena do několika hlavních činností (řemeslná výroba, těžba, atd.). Bylo rozhodnuto mít místo dvou hlavních kategorií (jedna pro povolání, druhá pro činnosti) vše v jedné, přičemž strukturující hesla jsou činnosti, pod kterými jsou jak jednotlivá povolání, tak hesla s činnostmi související (kamenické značky, šperkařské techniky, atd.).</p>\n' +
          '<h4 class="code-line"  data-line-start="90"  data-line-end="91" ><a id="211_Spolenost_11_90"></a>2.11. Společnost (11)</h4>\n' +
          '<p class="has-line-data" data-line-start="91" data-line-end="92">V jedenácté větvi se nalézají hesla týkající se společnosti. Větev seskupuje hesla pro sociální stratifikaci (jak obecná, tak konkrétní), různé typy práva a právních institutů a různých společenských zřízení.</p>\n' +
          '<h3 class="code-line"  data-line-start="94"  data-line-end="95" ><a id="30_Bibliografick_soupis_literatury_94"></a>3.0. Bibliografický soupis literatury:</h3>\n' +
          '<p class="has-line-data" data-line-start="95" data-line-end="96">Databáze národních autorit ČR. <em>Národní autority ČR</em> [online]. Praha: Národní knihovna ČR, 2019 [cit. 2019-06-20]. Dostupné z: <a href="https://aleph.nkp.cz/F/?func=file&amp;file_name=find-b&amp;local_base=aut">https://aleph.nkp.cz/F/?func=file&amp;file_name=find-b&amp;local_base=aut</a></p>\n' +
          '  <p class="has-line-data" data-line-start="97" data-line-end="98">FISH Archaeological Objects Thesaurus, 2019 [online]. London: Collections Trust. [cit. 2019-09-10]. Dostupné z: <a href="http://thesaurus.historicengland.org.uk/thesaurus.asp?thes_no=144&amp;thes_name=FISH%20Archaeological%20Objects%20Thesaurus">http://thesaurus.historicengland.org.uk/thesaurus.asp?thes_no=144&amp;thes_name=FISH%20Archaeological%20Objects%20Thesaurus</a>)</p>\n' +
          '<p class="has-line-data" data-line-start="99" data-line-end="100">HLOŽEK, Martin, 2008. <em>Encyklopedie moderních metod v archeologii: Archeometrie</em>. Praha: Nakladatelství Libri. ISBN 978-80-7277-230-8.</p>\n' +
          '<p class="has-line-data" data-line-start="101" data-line-end="102">JOHN, Jan, Ondřej CHVOJKA a Tereza KRIŠTUFOVÁ, 2009. <em>Česko-anglicko-německý slovníček pro studenty archeologie</em>. Plzeň: Katedra antropologie, Fakulta filozofická, Západočeská univerzita v Plzni. ISBN 978-80-7043-843-5</p>\n' +
          '<p class="has-line-data" data-line-start="103" data-line-end="104">KOŠNAR, Lubomír, 2010. <em>Německo-český a česko-německý archeologický slovník</em>. Praha 2010. ISBN 978-80-246-1757-2</p>\n' +
          '<p class="has-line-data" data-line-start="105" data-line-end="106">KRIŠTUF, Petr, Tereza ZÍKOVÁ a kol. 2015. <em>Výzkum krajiny: vybrané antropologické a archeologické metody</em>. Plzeň: Západočeská univerzita v Plzni. ISBN 978-80-261-0475-9</p>\n' +
          '<p class="has-line-data" data-line-start="107" data-line-end="108">KUNA, Martin a kolektiv. 2007. <em>Archeologie pravěkých Čech. /1, Pravěký svět a jeho poznání</em>. Praha: Archeologický ústav AV ČR, Praha, v. v. i. ISBN 978-80-86124-75-9.</p>\n' +
          '<p class="has-line-data" data-line-start="109" data-line-end="110">NEUSTUPNÝ, Evžen, 2007. <em>Metoda archeologie</em>. Plzeň: Aleš Čeněk. ISBN 978-80-7380-075-8</p>\n' +
          '<p class="has-line-data" data-line-start="111" data-line-end="112">NEUSTUPNÝ, Evžen, 2010. <em>Teorie archeologie</em>. Plzeň: Vydavatelství a nakladatelství Aleš Čeněk. ISBN 978-80-7380-244-8</p>\n' +
          '<p class="has-line-data" data-line-start="113" data-line-end="114">PODBORSKÝ, Vladimír, 2006. <em>Dějiny pravěku a rané doby dějinné</em>. Praha: Ústav archeologie a muzeologie, Filozofická fakulta Masarykovy univerzity. ISBN 80-210-4153-6</p>\n' +
          '<p class="has-line-data" data-line-start="115" data-line-end="116">RAMEŠ, Václav, 2005. <em>Slovník pro historiky a návštěvníky archivů</em>. Praha: Nakladatelství Libri. ISBN 80-7277-175-2.</p>\n' +
          '<p class="has-line-data" data-line-start="117" data-line-end="118">SCHEBEK, Adolf, 2007. <em>Deutsch-tschechische archäologische Terminologie</em>. Praha: Archeologický ústav AV ČR Praha. ISBN 978-80-86124-74-2</p>\n' +
          '<p class="has-line-data" data-line-start="119" data-line-end="120">SKLENÁŘ, Karel, 1989. <em>Archeologický slovník. Část 1., Kamenné artefakty</em>. Praha: Národní muzeum.</p>\n' +
          '<p class="has-line-data" data-line-start="121" data-line-end="122">SKLENÁŘ, Karel a Michal LUTOVSKÝ, 1992. <em>Archeologický slovník. Část 2, Kovové artefakty 1.,  pravěk a raný středověk</em>. Praha: Národní muzeum.</p>\n' +
          '<p class="has-line-data" data-line-start="123" data-line-end="124">SKLENÁŘ, Karel, 1998. <em>Archeologický slovník. Část 3, Keramika a sklo</em>. Praha: Národní muzeum.</p>\n' +
          '<p class="has-line-data" data-line-start="125" data-line-end="126">SKLENÁŘ, Karel, 2000. <em>Archeologický slovník. Část 4, Kostěné artefakty</em>. Praha: Národní muzeum.</p>\n' +
          '<p class="has-line-data" data-line-start="127" data-line-end="128">SKLENÁŘ, Karel, Zuzana SKLENÁŘOVÁ a Miloslav SLABINA, 2002. <em>Encyklopedie pravěku v Čechách, na Moravě a ve Slezsku</em>. Praha: Libri. ISBN 80-7277-115-9</p>\n' +
          '<p class="has-line-data" data-line-start="129" data-line-end="130">Sociologický ústav AV ČR, v.v.i., 2017. <em>Sociologická encyklopedie</em> [online]. NEŠPOR, Zdeněk (ed.). Praha: Sociologický ústav AV ČR. [cit. 2019-09-10]. Dostupné z: <a href="https://encyklopedie.soc.cas.cz/w/Hlavn%C3%AD_strana">https://encyklopedie.soc.cas.cz/w/Hlavn%C3%AD_strana</a></p>\n' +
          '<p class="has-line-data" data-line-start="131" data-line-end="132"><em>Wikipedia: otevřená encyklopedie</em>, 2001- [online]. San Francisco (CA): Wikimedia Foundation. [cit. 2019-06-20]. Dostupné z: <a href="https://www.wikipedia.org/">https://www.wikipedia.org/</a></p>\n'
      }}
    />
  )
}
