spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}:${DB_PORT}/${DB_NAME}?currentSchema=thesaurus
    username: ${DB_USER}
    password: ${DB_PASSWORD}
graphql:
  servlet:
    max-query-depth: 20
    tracing-enabled: false
    mapping: /api/graphql
    corsEnabled: false
  playground:
    endpoint: /api/graphql
server:
  http2:
    enabled: true

url-base: http://teater.aiscr.cz/