spring:
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    name: mainPool
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        show_sql: false
        use_sql_comments: true
        format_sql: true

graphql:
  url: api/graphql

graphiql:
  mapping: /api/graphiql
  endpoint: /api/graphql
  static:
    basePath: /
  enabled: true
  pageTitle: GraphiQL

#TODO: choose placeholder color
placeholder_type:
  "idk m8"